### ISSUE TITLE
CharredDesert-0.1.0-mac

### ISSUE THREAD

**Issue by cfoulc** [JerrySievert/CharredDesert#1]
[CharredDesert-0.1.0-mac.zip](https://github.com/JerrySievert/CharredDesert/files/1693113/CharredDesert-0.1.0-mac.zip)

**Comment by nay-seven** [comment]
Thanks for the release clement !
And Thanks Jerry ! Not module will be useful sometimes ;-)

**Comment by JerrySievert** [comment]
there will be official releases, this is just an experimental set of modules so far. I wanted to add 1-2 more before a real release.

at that point, all platforms.

**Comment by JerrySievert** [comment]
more modules added, and plugins for all platforms have been released.

going to go ahead and close this one.

**Comment by JerrySievert** [comment]
a couple more modules coming, btw!
