### ISSUE TITLE
oscar2 mix control not working as expected

### ISSUE THREAD

**Issue by glocke01** [JerrySievert/CharredDesert#12]
![oscar2_bug](https://user-images.githubusercontent.com/12255580/60542121-2b53d600-9ce1-11e9-8b74-fbb7c51a80ef.png)

With the mix knob at full, the second oscillator is approximately 10% (at a guess). 

running rack 1.1.1 on ubuntu 18.04.1 LTS with Intel® Core™ i7-6700 CPU @ 3.40GHz × 8 . problem remained unchanged with threads 1 or 4.

**Comment by JerrySievert** [comment]
thanks, I'll take a look and see if I can get a new release with it fixed soon.

**Comment by JerrySievert** [comment]
found the issue - it occurred when I ported from 0.6 to 1.0 - I've fixed and will ask for rack to update tonight.

I'll keep the issue open until it is released.

**Comment by JerrySievert** [comment]
modules released, going to go ahead and close this now.
