### ISSUE TITLE
[1.0] Basic CV module does not distinguish between 2 channels' switches

### ISSUE THREAD

**Issue by Nareese** [JerrySievert/CharredDesert#14]
After upgrading my Rack install to 1.0+, a basic 2 channel CV module I had in my "screwing around" rack no longer functions as expected.  The module that was in my pre-1.0 rack, the channel 2 light is on, but clicking on the switch for channel 2 causes channel 1 to switch on and off.  If I connect a patch cable to channel 2's output, it is outputting cv, and the level pot adjusts the voltage correctly.  Only the switch behaves incorrectly.

Thinking that it might be something weird with the module because of config from my pre-1.0 rack, I tested adding a new CV module to the rack, and it behaves exactly the same, except that the freshly loaded module's channel 2 is in the default off state, and cannot be turned on, obviously (clicking it toggles channel 1, same as my existing module).  I also tested this in a completely fresh rack with File->New.  All behave identically, so I don't think it's something specific to my config or my rack.

Possible cause?  should be `CVModule::SWITCH + i` at https://github.com/JerrySievert/CharredDesert/blob/321c938cddcea414d6da1fbcb6cf4d07ff870f15/src/view/CV.cpp#L18

Tested with:

Windows 7
Rack 1.0, 1.1.0, 1.1.1 (current)
CD modules 1.0.0

**Comment by JerrySievert** [comment]
thanks, I'll take a look and get an update out soon.

**Comment by JerrySievert** [comment]
yup, exactly it.  I ripped too much out of the param definition when I ported to 1.0.

thanks for the report, I'll see about getting it out asap - will send it to rack for update tonight.  leaving the issue open until it's resolved.

**Comment by Nareese** [comment]
Build and ship of the 1.0.1 release happened this afternoon, and the module is now functioning as expected.  Thanks for the fix!
