### ISSUE TITLE
v2: References to fonts stored across frames crashes VST

### ISSUE THREAD

**Issue by cschol** [JerrySievert/CharredDesert#17]
References to fonts [cannot be stored across frames](https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames) in `v2`.

For example:

```
FrequencyDisplay ( ) {
   value = NULL;
   font = APP->window->loadFont(asset::plugin(pluginInstance, "res/digit.ttf"));
}
```

**Comment by JerrySievert** [comment]
changed
