### ISSUE TITLE
Noise module

### ISSUE THREAD

**Issue by ghost** [JerrySievert/CharredDesert#2]
Hey!

Is it possible that the labels are inverted for "white/pink" noise switch?

**Comment by JerrySievert** [comment]
hm. I checked it a few times, and pink noise was coming out sampled as pink, and white as white, but I'm happy to check again.

sorry for the delay, not getting emails from GitHub for the modules for some reason (though am for major projects I maintain)

**Comment by ghost** [comment]
yea pls do.. maybe I m mistaken.. but I thought its better to let you know ;)

**Comment by JerrySievert** [comment]
this will be fixed with the 0.6.0 release, which will come out ... well, you know when :)
