### ISSUE TITLE
EQ [feature request]

### ISSUE THREAD

**Issue by Eurikon** [JerrySievert/CharredDesert#8]
Hi there!
It would be nice to have a CV input for FREQ knob. 
To enable  slow modest modulation on that sweet spot:)

**Comment by JerrySievert** [comment]
sorry, didn't see the issue until now (not sure why GitHub doesn't send me notifications for this repo).

that's a great idea, I'll look to see what it would take to fit it in (physically)

**Comment by Eurikon** [comment]
no problem, 
thanks!:)

**Comment by JerrySievert** [comment]
how much wobble are you looking for?  if I implement it as a straight up addition, it will end up at +/- 10 which isn't really much to work with.  I can always multiply the input by 10, and you could use an attenuator for smaller values.

**Comment by Eurikon** [comment]
Hi, well i haven't really thought about an exact value. 
It should be creatively noticeable (ie: to achieve a sweep).

**Comment by JerrySievert** [comment]
I ended up having the cv affect the whole range for both frequency and q, so you'll want to use an attenuator to range that for smaller sweeps.  I'll ask vcvrack to update with the newest version.

**Comment by Eurikon** [comment]
Thanks Jerry! :)

**Comment by JerrySievert** [comment]
it's live, closing
